# Generated by Django 3.2 on 2022-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmanagement',
            name='type',
            field=models.CharField(choices=[('socialmedia', 'socialmedia'), ('videogame', 'videogame'), ('metaverse', 'metaverse')], max_length=30, verbose_name='type'),
        ),
    ]
