# Generated by Django 3.2 on 2022-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_linkmanagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user')], max_length=100, null=True),
        ),
    ]
