# Generated by Django 3.2 on 2022-06-20 06:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to=account.models.upload_image_to, verbose_name='image')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
                'db_table': 'logo',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
