# Generated by Django 3.2 on 2022-06-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220620_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='title',
        ),
    ]
