# Generated by Django 3.2 on 2022-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_logo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoname',
            field=models.CharField(max_length=256, null=True, verbose_name='video name'),
        ),
    ]
