# Generated by Django 3.2 on 2022-06-21 11:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_video_videoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=256, null=True, upload_to=account.models.upload_video_to, validators=[account.models.validate_file_extension], verbose_name='video'),
        ),
    ]
