# Generated by Django 3.2 on 2022-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220621_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecommon',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='content'),
        ),
    ]
