# Generated by Django 3.2 on 2022-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_pagecommon_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecommon',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='content'),
        ),
    ]
