# Generated by Django 3.2 on 2022-06-22 09:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_pagecommon_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecommon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_image_to, verbose_name='image'),
        ),
    ]
