# Generated by Django 3.2 on 2022-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_pagecommon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmanagement',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='key'),
        ),
    ]
