# Generated by Django 3.2 on 2022-06-23 08:36

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_pagecommon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmanagement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_image_to, verbose_name='image'),
        ),
    ]
