# Generated by Django 3.2 on 2022-06-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_linkmanagement_image'),
        ('account', '0012_alter_linkmanagement_key'),
    ]

    operations = [
    ]
