# Generated by Django 3.2 on 2022-06-24 05:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20220623_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=account.models.upload_video_to, validators=[account.models.validate_file_extension], verbose_name='video'),
        ),
    ]
