# Generated by Django 3.2 on 2022-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='image',
        ),
        migrations.AddField(
            model_name='logo',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='logo',
            name='title',
            field=models.CharField(max_length=2000, null=True, verbose_name='title'),
        ),
    ]
