# Generated by Django 3.2 on 2022-07-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_linkmanagement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linktype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'link type',
                'verbose_name_plural': 'link types',
                'db_table': 'link_types',
            },
        ),
        migrations.AlterField(
            model_name='linkmanagement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='account.linktype', verbose_name='type'),
        ),
    ]
