# Generated by Django 3.2 on 2022-07-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_logo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmanagement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='account.linktype', verbose_name='type'),
        ),
    ]
