# Generated by Django 3.2 on 2022-07-05 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_linkmanagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmanagement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='links', to='account.linktype', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='upload by'),
        ),
    ]
